name: Build Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v3.5.3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Dolibarr version
        id: dolibarr-version
        run: echo "::set-output name=dolibarr-version::$(curl -sX GET https://raw.githubusercontent.com/tuxgasy/docker-dolibarr/master/versions.sh | grep 'DOLIBARR_LATEST_TAG=' | awk '{print $2}' FS='["]')"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: vincowl/dolibarr-docker:latest, vincowl/dolibarr-docker:${{ steps.dolibarr-version.outputs.dolibarr-version}}
